sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "liusan666"
  redis:
    host: localhost
    port: 6379
    auth: liusan666
    database: 1
  wechat:
    appid: wxdea05b187a1c725d
    secret: f55aca1bd0a1d52737638faff5a70ace
#    mchid:
#    mchSerialNo:
#    privateKeyFilePath:
#    apiV3Key:
#    weChatPayCertFilePath:
    notifyUrl: http://36f8dd01.r24.cpolar.top/notify/paySuccess
    refundNotifyUrl: http://36f8dd01.r24.cpolar.top/notify/refundSuccess